FROM node:22

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY . .

ARG NODE_ENV
ARG PORT
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_PORT
ARG DATABASE_NAME
ARG DATABASE_HOST
ARG JWT_SECRET
ARG JWT_EXPIRES_IN
ARG JWT_SECRET_INVITE

ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
ENV JWT_SECRET_INVITE=${JWT_SECRET_INVITE}

RUN echo "NODE_ENV=${NODE_ENV}"
RUN echo "PORT=${PORT}"
RUN echo "DATABASE_USER=${DATABASE_USER}"
RUN echo "DATABASE_PASSWORD=${DATABASE_PASSWORD}"
RUN echo "DATABASE_PORT=${DATABASE_PORT}"
RUN echo "DATABASE_NAME=${DATABASE_NAME}"
RUN echo "DATABASE_HOST=${DATABASE_HOST}"
RUN echo "JWT_SECRET=${JWT_SECRET}"
RUN echo "JWT_EXPIRES_IN=${JWT_EXPIRES_IN}"
RUN echo "JWT_SECRET_INVITE=${JWT_SECRET_INVITE}"

RUN npm run build

EXPOSE ${PORT}

CMD npm run db:create && npm run migration:run && npm run start:prod
