name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ actions.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ actions.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t $DOCKER_USERNAME/schoolpost:latest \ 
            --build-arg NODE_ENV=${{ actions.NODE_ENV }} \
            --build-arg DATABASE_HOST=${{ actions.DATABASE_HOST }} \
            --build-arg DATABASE_USER=${{ actions.DATABASE_USER }} \
            --build-arg DATABASE_PASSWORD=${{ actions.DATABASE_PASSWORD }} \ 
            --build-arg DATABASE_PORT=${{ actions.DATABASE_PORT }} \ 
            --build-arg PORT=${{ actions.PORT }} \ 
            --build-arg JWT_SECRET=${{ actions.JWT_SECRET }} \ 
            --build-arg JWT_EXPIRES_IN=${{ actions.JWT_EXPIRES_IN }} \ 
            .
          docker push $DOCKER_USERNAME/pettechstock:latest
